//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminNotice
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Notice_SrNo { get; set; }
        public string Notice_Title { get; set; }
        public string Notice_Description { get; set; }
        public Nullable<System.DateTime> Notice_Date { get; set; }
        public string Department { get; set; }
        public string Notice_Type { get; set; }
        public string Notice_Status { get; set; }
        public byte[] NoticeFile_Upload { get; set; }
        public Nullable<bool> Notice_New { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
