//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminNotice
    {
        public int Id { get; set; }
        public Nullable<int> NoticeTypeId { get; set; }
        public string Notice_title { get; set; }
        public Nullable<System.DateTime> Notice_Date { get; set; }
        public Nullable<int> Department { get; set; }
        public byte[] NoticeDocumentFile { get; set; }
        public string NoticeDocumentName { get; set; }
        public string NoticeDocumentFileType { get; set; }
        public Nullable<bool> NoticeNewTag { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
