//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantBankDetail
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string BankName { get; set; }
        public string BBName { get; set; }
        public string BBAddress { get; set; }
        public string IFSC_Code { get; set; }
        public string AccountHolderName { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    }
}
