//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantUploadDoc
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public byte[] ProjectReport { get; set; }
        public byte[] ProposedPlanLandUses { get; set; }
        public byte[] Memorendum { get; set; }
        public byte[] ScanPAN { get; set; }
        public byte[] ScanAddressProof { get; set; }
        public byte[] BalanceSheet { get; set; }
        public byte[] ITReturn { get; set; }
        public byte[] ExperienceProof { get; set; }
        public byte[] ApplicantEduTechQualification { get; set; }
        public byte[] PreEstablishedIndustriesDoc { get; set; }
        public byte[] FinDetailsEstablishedIndustries { get; set; }
        public byte[] OtherDocForProposedIndustry { get; set; }
        public byte[] ScanCastCert { get; set; }
        public byte[] ScanID { get; set; }
        public byte[] AllotmentLetter { get; set; }
        public byte[] LandEquitionDocProof { get; set; }
        public byte[] DocProofForIndustrialEstablishedOutsideGida { get; set; }
        public byte[] ApplicantPhoto { get; set; }
        public byte[] ApplicantSignature { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
