//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantUploadDoc
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public byte[] ProjectReport { get; set; }
        public byte[] ProposedPlanLandUses { get; set; }
        public byte[] Memorendum { get; set; }
        public byte[] ScanPAN { get; set; }
        public byte[] ScanAddressProof { get; set; }
        public byte[] BalanceSheet { get; set; }
        public byte[] ITReturn { get; set; }
        public byte[] ExperienceProof { get; set; }
        public byte[] ApplicantEduTechQualification { get; set; }
        public byte[] PreEstablishedIndustriesDoc { get; set; }
        public byte[] FinDetailsEstablishedIndustries { get; set; }
        public byte[] OtherDocForProposedIndustry { get; set; }
        public byte[] ScanCastCert { get; set; }
        public byte[] ScanID { get; set; }
        public byte[] BankVerifiedSignature { get; set; }
        public byte[] DocProofForIndustrialEstablishedOutsideGida { get; set; }
        public byte[] ApplicantPhoto { get; set; }
        public byte[] ApplicantSignature { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ProjectReportFileName { get; set; }
        public string ProjectReportFileType { get; set; }
        public string ProposedPlanLandUsesFileName { get; set; }
        public string ProposedPlanLandUsesFileType { get; set; }
        public string MemorendumFileName { get; set; }
        public string MemorendumFileType { get; set; }
        public string ScanPANFileName { get; set; }
        public string ScanPANFileType { get; set; }
        public string ScanAddressProofFileName { get; set; }
        public string ScanAddressProofFileType { get; set; }
        public string BalanceSheetFileName { get; set; }
        public string BalanceSheetFileType { get; set; }
        public string ITReturnFileName { get; set; }
        public string ITReturnFileType { get; set; }
        public string ExperienceProofFileName { get; set; }
        public string ExperienceProofFileType { get; set; }
        public string ApplicantEduTechQualificationFileName { get; set; }
        public string ApplicantEduTechQualificationFileType { get; set; }
        public string PreEstablishedIndustriesDocFileName { get; set; }
        public string PreEstablishedIndustriesDocFileType { get; set; }
        public string FinDetailsEstablishedIndustriesFileName { get; set; }
        public string FinDetailsEstablishedIndustriesFileType { get; set; }
        public string OtherDocForProposedIndustryFileName { get; set; }
        public string OtherDocForProposedIndustryFileType { get; set; }
        public string ScanCastCertFileName { get; set; }
        public string ScanCastCertFileType { get; set; }
        public string ScanIDFileName { get; set; }
        public string ScanIDFileType { get; set; }
        public string BankVerifiedSignatureFileName { get; set; }
        public string BankVerifiedSignatureFileType { get; set; }
        public string DocProofForIndustrialEstablishedOutsideGidaFileName { get; set; }
        public string DocProofForIndustrialEstablishedOutsideGidaFileType { get; set; }
        public string ApplicantPhotoFileName { get; set; }
        public string ApplicantPhotoFileType { get; set; }
        public string ApplicantSignatureFileName { get; set; }
        public string ApplicantSignatureFileType { get; set; }
    }
}
