//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantDetail
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FullApplicantName { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string SName { get; set; }
        public Nullable<System.DateTime> ApplicantDOB { get; set; }
        public string Gender { get; set; }
        public string Category { get; set; }
        public string Nationality { get; set; }
        public string AdhaarNumber { get; set; }
        public string PAN { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string EmailId { get; set; }
        public string Religion { get; set; }
        public string SubCategory { get; set; }
        public string CAddress { get; set; }
        public string PAddress { get; set; }
        public string IdentiyProof { get; set; }
        public string ResidentialProof { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    }
}
