//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantPlotDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AppliedFor { get; set; }
        public string SchemeType { get; set; }
        public string SchemeName { get; set; }
        public string PlotRange { get; set; }
        public string PlotArea { get; set; }
        public string SectorName { get; set; }
        public string EstimatedRate { get; set; }
        public string PaymentSchedule { get; set; }
        public Nullable<decimal> TotalInvestment { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> ApplicationFee { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> EarnestMoney { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string IndustryOwnership { get; set; }
        public string UnitName { get; set; }
        public string SignatryName { get; set; }
        public Nullable<System.DateTime> SignatryDateOfBirth { get; set; }
        public string SignatryPresentAddress { get; set; }
        public string SignatryPresentPhoneNumber { get; set; }
        public string SignatryPermanentAddress { get; set; }
        public string SignatryPermanentPhoneNumber { get; set; }
        public string RelationshipStatus { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    }
}
